name: neurokinematics_ci
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas=2.3.3
  - matplotlib
  - h5py
  - pytables
  - scikit-learn
  - datajoint
  - dask
  - dask-jobqueue
  - dask-ml
  - mne
  - xmltodict
  - xarray
  - zarr
  - pyyaml
  - pytest
  - pip
  - pip:
      - open-ephys-python-tools
      - spikeinterface
      - e .