name: climbing
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas=2.3.3
  - matplotlib
  - h5py
  - pytables
  - psutil
  - scikit-learn
  - datajoint
  - dask
  - dask-jobqueue
  - dask-ml
  - mne
  - xmltodict
  - xarray
  - zarr
  - pyyaml
  - pytest
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - pip:
      - kilosort[gui]
      - open-ephys-python-tools
      - spikeinterface